CC = g++
FLAGS = -Wall -O3

HEADER = timer.h 
LIB = lib

FACTORIAL = factorials
FACTORIALED = $(LIB)/$(FACTORIAL)
FIBONACCI = fibonacci
FIBONACCIED = $(LIB)/$(FIBONACCI)

all: $(FIBONACCI)

$(FACTORIAL): $(FACTORIAL).cpp
	@$(CC) -o $(FACTORIALED) $(FLAGS) $(FACTORIAL).cpp
	@./$(FACTORIALED)

$(FIBONACCI): $(FACTORIAL).cpp
	@$(CC) -o $(FIBONACCIED) $(FLAGS) $(FIBONACCI).cpp
	@./$(FIBONACCIED)
